version: '3'

services:
  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
      - .env.postgres
    ports:
      - 8080:8080
    restart: on-failure:60
    volumes:
      - .:/usr/src/app

  db:
    image: postgres:10.5-alpine
    env_file:
      - .env
      - .env.postgres
